# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: none

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    system_package=''
    system_package='--system-site-packages';
    echo "Installing system packages";

    python3 -m venv ${system_package} $(Build.BinariesDirectory)/venv

    source $(Build.BinariesDirectory)/venv/bin/activate
    echo "Virtual environment: ${VIRTUAL_ENV}"
    pip install -U pip setuptools wheel
  displayName: Create virtual environment

- script: |
    source $(Build.BinariesDirectory)/venv/bin/activate
    echo "Virtual environment: ${VIRTUAL_ENV}"
    pip install pylint

    cd . && find . -type d \( -path ./.git -o -path ./dist -o -path ./builds \) -prune -o -name '*.py' -print0 | xargs -0 pylint -j 0 --disable=R0913,E0401,R0902,R0801,R0903,C0301,W0703,R1710,C0114

    exit 0
  displayName: SoftPylint
  continueOnError: true

